### PR TITLE
Adds the capability to disable SSL verification for postgres 

### PR DESCRIPTION
**Pull request by fcristovao**
* README update still missing

Also, please check the parseTags function, as I think there was a bug there.

### CODE REVIEW

**Comment by djui** [comment]
The intention was to use [Struct tags](https://golang.org/pkg/reflect/#StructTag) values in fragment rather than query. Which of course highlights documentation could be improved. A query and fragment in this case could look like: `...?sslmode=disable#tables=t1,t2,t3`. So `tables=t1,t2,t3` is the none quoted form of a struct tag, e.g.

```go
type foo struct { 
    Foo string `db:"foo" json:"foo,omitempty" yaml:"foo,omitempty"`
}
```

Also see more detailed information about use cases https://sosedoff.com/2016/07/16/golang-struct-tags.html.

# However

This still leaves you valid point that the parsing has a bug: `,` can't be used (and isn't even) for separating K-V pairs _as well as_ Vs. So I'm not sure what's best to do here. One could use `,` for value delimiter and `;` for k-v delimiter. (I would like to avoid the confusion with a query string syntax's as it's not expressive enough, and could get confusing for the http resource). The good thing with the comma was that SQL already knows this to be invalid for a table name; however a `&`, `;`,`+`,`|` should also work.

Independent of the chosen syntax, one could question of the `dbparam` query string should be even exposed and maybe also done in the `fragment`.

I solved/achieved this for now in https://github.com/betalo-sweden/await/pull/7.

**Comment by djui** [comment]
Btw, the SSL issue is solved via I solved/achieved this for now in https://github.com/betalo-sweden/await/pull/7.

**Comment by fcristovao** [comment]
Well, from the usages I've seen in [here](https://en.wikipedia.org/wiki/Fragment_identifier) of Fragments:
> http://example.com/bar.webm#t=40,80&xywh=160,120,320,240
> http://example.org/doc.pdf#view=fitb&nameddest=Chapter3
I would say that, at least, it isn't a surprise to use `&` as separators of keys, and `,` for value separators.

My suggestion would then to only keep https://github.com/betalo-sweden/await/pull/5/files#diff-7ddfb3e035b42cd70649cc33393fe32cR157 in the PR, and the rest of the stuff in #7

**Comment by fcristovao** [comment]
I'm closing this one in favor of #8

**Pull request closed without merging**
