### PR TITLE
Drain http response body and disable keep-alive

### LINKED ISSUE #27: How to prevent errors "Connection reset by peer" at docker container
Hi,

When I use await for http resource, an error occurred at docker container below:

> ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:13

Could you tell me how to prevent it?

### PR DESCRIPTION
**Pull request by djui**
It seems some http server throw `ECONNRESET` if the connection is reset before the entire response is read.

Might fix #27.

### CODE REVIEW

**Comment by djui** [comment]
I would like to first have a reproducible test (or http server) to minimize the changes. Currently it feels all three changes in themselves should be enough to not see the problem.

**Comment by HaraldNordgren** [comment]
Close these?

**Comment by djui** [comment]
@HaraldNordgren I guess yes. By now I didn't get any feedback from the original issue poster.

**Comment by HaraldNordgren** [comment]
@djui Found it here: https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Abetalo-sweden. It may or may or not worth it to go through it and close the ones you can.

**Pull request closed without merging**
